Работа по спринту #7 на ревью
artwist-polyakov/MovieQuiz-ios pull request #5
Opened 2023-04-13 10:35 UTC by artwist-polyakov

2023-04-13 14:12 UTC, mmbabaev requested changes

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var questionFactory: QuestionFactoryProtocol?
Для информации, можно также создавать такие свойства с помощью lazy:
```
private lazy var questionFactory: QuestionFactory {
    QuestionFactoryImpl(delegate: self
}
```

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    var correctAnswers: Int = 0
Здесь можно добавить private

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        alert.show(viewController: viewController! as! UIViewController)
так делать неправильно, нужно, чтобы Presenter не знал ничего о типе своей view, о UIKit. 

Варианты как сделать: 
1) Создавать `alertPresenter` вне `Presenter`, в `ViewController` и передавать при инициализации самого себя 
2) Работать с AlertPresenter в UIViewController. Из Presenter передавать `AlertModel`. Сейчас не хаватает этой структуры, оно должно содержать данные для отображения конкретного алерта.

В любом случае стоит переписать `AlertPresenter`

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +//        print("Я нажата: ДА")
лучше удалять ненужные комментарии

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            let totalPlaysCountLine = "Количество сыгранных квизов:\(statisticService.gamesCount)"
Для информации: можно использовать тройные кавычки
```
let banner = """
          __,
         (           o  /) _/_
          `.  , , , ,  //  /
        (___)(_(_/_(_ //_ (__
                     /)
                    (/
        """
```

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            }
скачет форматирование.
Предлагаю использовать `cmd + A`, `ctrd + I` , так будет легче читать код

Для информации: в реальных проектах часто используют лифтеры/форматеры, типа библиотек SwiftLint / SwiftFormatter

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +//            self.imageView.layer.masksToBounds = false
лучше убрать лишние комментарии

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var imageView: UIImageView!
Непонятно для чего это изменение

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            self.viewController?.imageView.layer.borderWidth = 0
Presenter должен вызвать функцию View, View сама настраивает UI

2023-04-13 14:12 UTC, mmbabaev commented on MovieQuizUITests/MovieQuizUITests.swift
> +
лучше удалять автосгенерированные комментари

2023-04-13 16:46 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var questionFactory: QuestionFactoryProtocol?
Начал править оставшиеся, не отмеченные важными пункты.
Не совсем понял комментарий, чего мы добьёмся таким объявлением. Можно я попрошу вас разжевать этот пункт прям для глупых людей.

2023-04-13 16:46 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    var correctAnswers: Int = 0
✅

2023-04-13 16:47 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        alert.show(viewController: viewController! as! UIViewController)
✅ Инициализировал AlertPresenter в  MovieQiuzViewController

2023-04-13 16:48 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +//        print("Я нажата: ДА")
✅ Конкретно эти я оставил, чтобы фиксировать нажатия на кнопку, мне кажутся они еще могут пригодиться. Остальное поудалял

2023-04-13 16:57 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            let totalPlaysCountLine = "Количество сыгранных квизов:\(statisticService.gamesCount)"
Буду знать, в других проектах использую их, тут они не пригодились бы

2023-04-13 17:00 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            }
✅ Расскажите порядок их установки, пожалуйста. Форматирование поправил

2023-04-13 17:01 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +//            self.imageView.layer.masksToBounds = false
✅

2023-04-13 17:04 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var imageView: UIImageView!
Потому что эти свойства являются частью протокола MovieQuizViewControllerProtocol. Понимаю, что можно и это улучшить тоже, но пока получилось так.

2023-04-13 17:14 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var imageView: UIImageView!
✅ Поправил

2023-04-13 17:14 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            self.viewController?.imageView.layer.borderWidth = 0
✅

2023-04-13 17:15 UTC, artwist-polyakov commented on MovieQuizUITests/MovieQuizUITests.swift
> +
Эти комментарии удалять не буду, чтобы в случае чего хотя бы сопоставить их с теорией — теории дано мало и она не улеглась, по сравнению, с теми же протоколами и паттернами

2023-04-14 16:02 UTC, mmbabaev approved these changes

2023-04-14 16:02 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var questionFactory: QuestionFactoryProtocol?
этот пункт необязательный, просто показал как можно еще сделать.
Из плюсов - мы "разгружаем" viewDidLoad, инициализация переменной лежит рядом с ее объявлением

2023-04-14 16:02 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private var questionFactory: QuestionFactoryProtocol?
также это не нужно в текущем кейсе, но главное предназначение lazy это то, что переменная будет инициализирована в момент использования

2023-04-14 16:04 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let alertPresenter = AlertPresenter()
здесь осталась неиспользуемая переменная, можно удалить.

 Такое легче было бы тебе самому увидеть, если бы прошлые дз были влиты в какую-то основную ветку. Я очень рекомендую делать так.

2023-04-14 16:04 UTC, mmbabaev approved these changes

2023-04-14 16:06 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private weak var viewController: MovieQuizViewControllerProtocol?
я предпочитаю называть переменные и сам тип как View, а не ViewController. 

View, c которой работает Presenter - означает не конкретный тип `UIView`, `UIViewController`, а означает компоненту, слой View из архитектуры MVP.

2023-04-14 17:24 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let alertPresenter = AlertPresenter()
> здесь осталась неиспользуемая переменная, можно удалить.
> 
> Такое легче было бы тебе самому увидеть, если бы прошлые дз были влиты в какую-то основную ветку. Я очень рекомендую делать так.

Тоже не уловил немного комментарий. У меня все ДЗ в принципе влиты в одну ветку, или надо было как-то по другому сделать ?

2023-04-14 17:26 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private weak var viewController: MovieQuizViewControllerProtocol?
> View, c которой работает Presenter - означает не конкретный тип `UIView`, `UIViewController`, а означает компоненту, слой View из архитектуры MVP.

Это наследие лекционного материала, тут ничего не поделать, мы называли переменные так, как их придумал создатель курса)

2023-04-14 17:27 UTC, artwist-polyakov commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let alertPresenter = AlertPresenter()
✅ переменную  удалил @mmbabaev

2023-04-14 22:05 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            }
В следующих проектах вы будете изучать подключение библиотек через Swift Package Manager. Пока если есть желание, можешь попробовать подключить их самостоятельно. Инструкции есть в описании репозиториев 

https://github.com/realm/SwiftLint
https://github.com/nicklockwood/SwiftFormat

2023-04-14 22:07 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let alertPresenter = AlertPresenter()
Про ветки: после каждого принятого дз нужно сливать PR в основную ветку (например, в project_sprint_3_start). Затем отводить из основной ветки следующий спринт. Он будет содержать только внесенные изменения

2023-04-15 08:32 UTC, merged